### ISSUE TITLE
When using address book on Aave governance payloads, flattening for verification generates too big file

### ISSUE THREAD

**Issue by eboadom** [bgd-labs/aave-address-book#16]
## Context

When flattening with Foundry a payload like the one [HERE](https://github.com/bgd-labs/aave-v3-listing-stewards/blob/master/src/contracts/savax/AaveV3SAVAXListingSteward.sol), `forge flatten contractPath` generates a really big Solitidy flattened file, due to the number of interfaces' dependencies of address book, and it even contains clash of dependencies because of duplications.

This is pretty inconvenient because as we know, it is worth it even to use address book in production payloads in some cases. But with this problem of flattening, and consequently not being able to do Etherscan verification, it is not possible to introduce address book.

###  Proposal
Needs some research. This would be solved if on flattening only the used interfaces dependencies (and I would say even better only the functions/structs used on those) would be included.

**Comment by sakulstra** [comment]
closing as there's not much we can do and we already removed some things to minify the included amount of artifacts.
