### ISSUE TITLE
AAVE Ecosystem Reserve: `0x25F2226B597E8F9514B3F68F00f494cF4f286491`

### ISSUE THREAD

**Issue by sakulstra** [bgd-labs/aave-address-book#34]
Add ecosystem reserve & controller to address book as suggested in #32

- AaveEcosystemReserve [0x25F2226B597E8F9514B3F68F00f494cF4f286491](https://etherscan.io/address/0x25F2226B597E8F9514B3F68F00f494cF4f286491)
- AaveEcosystemReserveController [0x3d569673dAa0575c936c7c67c4E6AedA69CC630C](https://etherscan.io/address/0x3d569673dAa0575c936c7c67c4E6AedA69CC630C#code)
- PolygonCollectorController [0xDB89487A449274478e984665b8692AfC67459deF](https://polygonscan.com/address/0xDB89487A449274478e984665b8692AfC67459deF#code)

We already have the controller in the address book here https://github.com/bgd-labs/aave-address-book/blob/main/src/AaveV2Ethereum.sol#L34 but we don't ship any interface for `COLLECTOR_CONTROLLER` - iirc the reason for that is that the interfaces accross pools are not consistent. Ethereum V2 supports streaming - afaik non of the others do.

There's two questions to answer:

1. Where to put `AAVE_ECOSYSTEM_RESERVE`?
a) we could add it to the `AaveV2Ethereum` library. It doesn't really belong there though.
b) we could add a new library especially for `AaveEcosystemReserve` containing the reserve and controller address
c) ...

2. Should we expose the interfaces if yes which ones and where? Is there a chance we could align them throughout pools?

**Comment by eboadom** [comment]
1. Maybe an `AaveMisc` library?
2. We should align yes, but for that, we need to upgrade first the Collector contracts in all non-Ethereum.
