### ISSUE TITLE
amoy testnet

### ISSUE THREAD

**Issue by byancad** [bgd-labs/aave-address-book#446]
with mumbai deprecated, the testnet contract addresses do not included one on amoy, that would be really helpful to have: https://docs.aave.com/developers/deployed-contracts/v3-testnet-addresses

**Comment by joelamouche** [comment]
That would be helpful for us too as we use Aave as an example on Amoy

**Comment by iamyeasin** [comment]
Yes, eagerly waiting for Amoy testnet to be deployed.

**Comment by KENILSHAHH** [comment]
Hi, i would like to contribute on adding support for Amoy testnet. It would be great if i could get to know on how to get started?

**Comment by sakulstra** [comment]
@brotherlymite can u take care?

**Comment by ijerkovic** [comment]
Hi, any progress on this one?

**Comment by sakulstra** [comment]
closing in favor of https://github.com/bgd-labs/aave-address-book/discussions/649 till we decide how to generally proceed with testnets.
