### ISSUE TITLE
Publicly-exposed channel-id

### ISSUE THREAD

**Issue by pegahcarter** [bgd-labs/aave-address-book#455]
Should be a secret.
https://github.com/bgd-labs/aave-address-book/blob/f73f77ca03f61c7bc3b6899d173e96ea200cf529/.github/workflows/cron.yml#L74

**Comment by sakulstra** [comment]
@pegahcarter why do you think it matters? It's a private slack channel noone has access to and even if one had, it only contains these auto-generated messages.

**Comment by pegahcarter** [comment]
I did not know that noone could have access to it- I saw it as an API key that gave any caller access. All good!
