### ISSUE TITLE
GHO addresses library

### ISSUE THREAD

**Issue by sakulstra** [bgd-labs/aave-address-book#482]
@miguelmtzinf noted that for avara it would be nice to have a `GHO` addresses directly accessible (not via assets library).

Putting them on `Misc` i was opposed, because:
1) it's a duplication of what we already have in assets
2) misc is used in almost every aave proposal and aave related ecosystem project. As solidity currently does not tree-shake interfaces / libraries at verification every addition bloats verification everywhere and creates noise on diffing.

That said, I think as a compromise - especially considering the growing importance of GHO - it could make sense to just create a seperate `GHOMainnet`, `GHOArbitrum`, ... and remove things like GHO, GSM, CCIP from Misc.

**Comment by eboadom** [comment]
As the main "unit" of address book are big enough subsystems, I'd say that probably makes sense to go that way
